name: pulse
title: Pulse
base: core22
version: git
contact: frederik.feichtmeier@gmail.com
summary: Weather app for the Linux Desktop.
description: |
  A beautiful weather app made with Flutter, and yaru.dart.
source-code: https://github.com/ubuntu-flutter-community/pulse
issues: https://github.com/ubuntu-flutter-community/pulse/issues
license: GPL-3.0+
icon: snap/gui/pulse.png

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.27.4
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  pulse:
    plugin: nil
    source: .
    after: [flutter-git]

    override-build: |
      set -eu
      flutter doctor
      flutter pub get
      export API_KEY=$API_KEY
      flutter build linux --release -v --dart-define=API_KEY="$API_KEY"
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

slots:
  pulse-dbus:
    interface: dbus
    bus: session
    name: org.feichtmeier.Pulse

apps:
  pulse:
    command: bin/pulse
    desktop: snap/gui/pulse.desktop
    extensions: [gnome]
    common-id: org.feichtmeier.Pulse
    plugs:
      - network
      - network-status
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
