name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: dart